4 lection2/02 skeleton
js-tasks-ru/htmlcss-20220317_nataliya-toumarkin pull request #8
Opened 2022-04-01 23:58 UTC by nataliya-toumarkin

2022-04-01 23:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-03 12:07 UTC, GSemikozov requested changes

2022-04-03 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__wrapper {
это не элемент скелетона, а сам скелетон = .skeleton. )
иначе в текущей реализации получается что используем элементы блока без самого блока

2022-04-03 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 597px;
это лишнее

2022-04-03 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton {
а это не блок = .skeleton, а элемент блока .skeleton__body

2022-04-03 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__headings span:nth-child(1) {
очень не универсальная схема (на этом месте может быть впоследствии любой элемент, и не обязательно span), и не обязательно с таким max-width

2022-04-03 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 172px;
лучше в процентах - при изменении размеров блока линии тоже будет пропорционально изменять ширину

2022-04-03 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 257px;
и тут.
достаточно выбрать одно - либо max-width либо width

2022-04-03 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 515px;
и тут та же история

2022-04-03 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__body span:nth-child(2) {
и тут

2022-04-03 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__headings span:nth-child(1) {
поэтому правильнее самой линии задать модификатор, который будет менять ширину (напр .skeleton__text_small)

2022-04-03 12:07 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__headings span:nth-child(2) {
тут то же самое что и выше

2022-04-04 12:48 UTC, nataliya-toumarkin commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 597px;
Не понимаю почему лишнее, оставила пока как есть

2022-04-04 12:48 UTC, nataliya-toumarkin commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__wrapper {
Исправила

2022-04-04 12:52 UTC, nataliya-toumarkin commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton {
Исправлено

2022-04-04 13:51 UTC, nataliya-toumarkin commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 257px;
Исправила

2022-04-04 13:51 UTC, nataliya-toumarkin commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 515px;
исправила

2022-04-04 13:51 UTC, nataliya-toumarkin commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__headings span:nth-child(2) {
исправила

2022-04-04 13:57 UTC, nataliya-toumarkin commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 172px;
Задала значение ширины линий-блоков в процентах

2022-04-04 14:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-04 14:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-04 18:16 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 597px;
поскольку нет смысла ограничивать блок который мы планируем переиспользовать - его размеры будут целиком и полностью зависеть от родителя / от контекста встраивания (вставили в контейнер половинчатой ширины - значит подстроимся; вставим в контейнер шириной более 1280px - значит растянемся по всей ширине; а при сужении расширении не будет никаких ограничений)

2022-04-07 16:34 UTC, GSemikozov approved these changes

2022-04-07 16:35 UTC, merged